Updated gdml to geometry as constructed for 2022 test beam
EinarElen/prototype-geometry pull request #16
Opened 2022-04-05 13:37 UTC by PeterGy

Redefined detecting layers as: 0.5 mm Al cover, 20 mm scintillator, 3 mm steel holding plate. In this order.
Changed absorber into a plate without holes, with thickness 20 mm, 
Added 20th absorber
Implemented x bar displacement constant
Added 8020 frame

Added 2 LYSO options, currently commented
Added code that could be used for absorber holes

2022-04-05 13:47 UTC, EinarElen commented
Hi, 

why have you deleted a bunch of files? e.g. the reference code and the figures?

2022-04-05 19:29 UTC, EinarElen requested changes
OK, I haven't had time to look at the documentation but here's my feedback.

Cheers!

2022-04-05 19:58 UTC, PeterGy commented
Great feedback. I shall address your comments in the form of an excellent fix.

2022-04-06 08:22 UTC, PeterGy commented on materials.gdml
> +         <fraction n="0.01" ref="Mn"/>
I looked up the definition on wikipedia. They did say it varies very little bit, and this was the simplest way of matching the general criteria.

2022-04-06 13:34 UTC, PeterGy commented on hcal_volumes.gdml
> +
Yes, they are both steel.

2022-04-06 13:38 UTC, PeterGy commented
All issues fixed in new push.

2022-05-06 12:17 UTC, EinarElen approved these changes

2022-05-06 12:17 UTC, EinarElen commented on userinfo.gdml
> +  <auxiliary auxtype="Author" auxvalue="Ruth Poettgen"/>
I guess we should update this before actually putting things into ldmx-sw

2022-05-06 12:18 UTC, merged